import Link from 'next/link'

export default function TermsPage() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=Lora:ital,wght@0,400;1,400&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
        body{background:#080510;color:#EDE8F5;font-family:'Lora',serif}
        h1,h2,h3{font-family:'Playfair Display',serif;color:#EDE8F5}
        p,li{line-height:1.8;color:rgba(220,210,245,0.75);margin-bottom:12px}
        h2{font-size:20px;margin:32px 0 12px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,0.08)}
        h3{font-size:16px;margin:20px 0 8px;color:rgba(200,180,255,0.8)}
        ul{padding-left:20px;margin-bottom:12px}
        a{color:rgba(150,100,255,0.8);text-decoration:none}
      `}</style>
      <div style={{minHeight:'100vh',background:'#080510'}}>
        <div style={{maxWidth:'760px',margin:'0 auto',padding:'60px 32px 100px'}}>
          <Link href="/" style={{fontFamily:'"Playfair Display",serif',fontSize:'18px',fontWeight:900,color:'rgba(200,180,255,0.4)',textDecoration:'none',letterSpacing:'1px',display:'block',marginBottom:'48px'}}>
            MYSTIC<span style={{fontSize:'11px',verticalAlign:'super',marginLeft:'2px',fontWeight:400}}>AI</span>
          </Link>
          <h1 style={{fontSize:'clamp(28px,5vw,42px)',fontWeight:900,marginBottom:'8px'}}>Terms of Service</h1>
          <p style={{color:'rgba(200,185,240,0.4)',fontStyle:'italic',marginBottom:'40px'}}>Last updated: March 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using Mystic AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use our Service.</p>

          <h2>2. Description of Service</h2>
          <p>Mystic AI provides AI-powered esoteric consultation services including tarot readings, astrology, numerology, compatibility analysis, and personalized PDF reports. All content is generated by artificial intelligence and is intended for entertainment and personal reflection purposes only.</p>

          <h2>3. Disclaimer</h2>
          <p>Mystic AI services are provided for entertainment purposes only. We do not guarantee the accuracy of any readings or predictions. Our services should not be used as a substitute for professional advice in medical, legal, financial, or psychological matters.</p>

          <h2>4. Subscriptions and Payments</h2>
          <p>We offer monthly subscription plans and one-time premium reports. Payments are processed securely through Paddle. Subscriptions automatically renew unless cancelled before the renewal date.</p>
          <ul>
            <li>Initiate Plan: monthly subscription with unlimited consultations</li>
            <li>Oracle Pro Plan: monthly subscription with all premium features</li>
            <li>Premium Reports: one-time payments for PDF reports</li>
          </ul>

          <h2>5. Refund Policy</h2>
          <p>Due to the digital nature of our services, all sales are final. However, we offer refunds in the following cases:</p>
          <ul>
            <li>Technical errors that prevented service delivery</li>
            <li>Duplicate charges</li>
            <li>Subscription cancellation within 24 hours of first charge</li>
          </ul>
          <p>To request a refund, contact us at support@mystic-ai.app within 7 days of purchase.</p>

          <h2>6. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years old to use our Service.</p>

          <h2>7. Intellectual Property</h2>
          <p>All content generated by Mystic AI is for your personal use only. You may not reproduce, distribute, or sell our content without written permission.</p>

          <h2>8. Limitation of Liability</h2>
          <p>Mystic AI shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid in the last 30 days.</p>

          <h2>9. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

          <h2>10. Contact</h2>
          <p>For questions about these Terms, contact us at: <a href="mailto:support@mystic-ai.app">support@mystic-ai.app</a></p>
        </div>
      </div>
    </>
  )
}